### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'started')

### ISSUE THREAD

**Issue by Vafelz** [Vafelz/VAFELZ-ALLAMMO#1]
[TypeError-GameController.txt](https://github.com/Vafelz/VAFELZ-ALLAMMO/files/13998628/TypeError-GameController.txt)

TypeError: Cannot read properties of undefined (reading 'started')
>  at GameController.validateQuestAssortUnlocksExist (C:\snapshot\project\src\controllers\GameController.ts:837:43)
    at GameController.gameStart (C:\snapshot\project\src\controllers\GameController.ts:213:18)
    at GameCallbacks.gameStart (C:\snapshot\project\src\callbacks\GameCallbacks.ts:63:29)
    at RouteAction.action (C:\snapshot\project\src\routers\static\GameStaticRouter.ts:49:47)
    at GameStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)
    at IncomingMessage.emit (node:events:513:28)

**Comment by Vafelz** [comment]
mod.ts missing questassort
